### ISSUE TITLE
Problem with entity interactions when Plushed is Installed

### ISSUE THREAD

**Issue by TabbyCatface** [EssieFir/Plushed#1]
I love this mode and adore each detail in it, but I simly can't play with it, because for some reason it disables my ability to interact with mobs using items or tools in any way: like shearing sheep, feeding animals, putting them on a leash, renaming with nametags, etc.

Here is my modlist:
- Minecraft 1.20.1
- Forge 47.2.20

- Fastload

- Plushed <<<<<<<<<<<<<<<<<<<<<

- Oculus
- Canary
- FPS Reducer
- Saturn
- Entity Culling
- Clumps
- Borderless Window

- Architectury API
- Collective lib
- Cloth Config API

- Better F3 Plus
- Better F3
- Rebind Narrator
- JEI
- Antique Atlas 4
- Falling Leaves (Forge)
- FallingTree

- playerAnimator
- Better Combat

- 3D Skin Layers
- Model Gap Fix
- First-person Model
- Better Third Person
- Shoulder Surfing Reloaded
- Not Enough Animations

**Comment by EssieFir** [comment]
Thanks for reporting!
Looks like this happens with the mod alone...
I'll look into this further when I have the time
